### ISSUE TITLE
Can't install 1.0 now

### ISSUE THREAD

**Issue by drder66** [clue/php-multicast-react#16] opened 2020-10-31 00:15 UTC
Seems to depend on react/event-loop, and requires a revison that is now too old to be available
Minimum version of event-loop seems to be 0.5.0 

Problem 1
    - Installation request for clue/multicast-react 1.0.0 -> satisfiable by clue/multicast-react[v1.0.0].
    - clue/multicast-react v1.0.0 requires react/event-loop ~0.3.0|~0.4.0 -> satisfiable by react/event-loop[0.3.x-dev, 0.4.x-dev, v0.3.0, v0.3.3, v0.3.4, v0.3.5, v0.4.0, v0.4.1, v0.4.2, v0.4.3] but these conflict with your requirements or minimum-stability.

**Comment by clue** [comment] 2020-11-03 07:59
Thanks for reporting, this has already been resolved via #11 and will be available in the next release :shipit: In the meantime you can also use `dev-master`.

Duplicate of #14

**Closed as completed by clue** 2020-11-03 07:59 UTC
Labels: question
